// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Y-s_x4QkYeOkmW2Dk04BtomhPkvoLUM',
    appId: '1:72652200079:web:380efe18f7eb03d494b8fa',
    messagingSenderId: '72652200079',
    projectId: 'safe-campus-63564',
    authDomain: 'safe-campus-63564.firebaseapp.com',
    storageBucket: 'safe-campus-63564.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5PaE082qzeVSGMqX1gPKwOksZ-lVU2xQ',
    appId: '1:72652200079:android:beba91c5aa2feeeb94b8fa',
    messagingSenderId: '72652200079',
    projectId: 'safe-campus-63564',
    storageBucket: 'safe-campus-63564.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxJKiiz2QHKSVwvDb9W7yFlvllgGvDP1U',
    appId: '1:72652200079:ios:b7feacfeb1a51e4194b8fa',
    messagingSenderId: '72652200079',
    projectId: 'safe-campus-63564',
    storageBucket: 'safe-campus-63564.firebasestorage.app',
    iosBundleId: 'com.example.reportScreenWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxJKiiz2QHKSVwvDb9W7yFlvllgGvDP1U',
    appId: '1:72652200079:ios:b7feacfeb1a51e4194b8fa',
    messagingSenderId: '72652200079',
    projectId: 'safe-campus-63564',
    storageBucket: 'safe-campus-63564.firebasestorage.app',
    iosBundleId: 'com.example.reportScreenWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Y-s_x4QkYeOkmW2Dk04BtomhPkvoLUM',
    appId: '1:72652200079:web:2d42c8fe3a410f0a94b8fa',
    messagingSenderId: '72652200079',
    projectId: 'safe-campus-63564',
    authDomain: 'safe-campus-63564.firebaseapp.com',
    storageBucket: 'safe-campus-63564.firebasestorage.app',
  );
}
